[package]
name = "xtask"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
toml_edit = "0.22.20"
prost-build = "0.13.1"
tonic-build = { version = "0.12.1", default-features = false, features = ["prost"] }
syn = "2.0.76"
prettyplease = "0.2.22"
