[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
toml_edit = "0.10"
prost-build = "0.9"
tonic-build = { version = "0.6", default-features = false, features = ["rustfmt", "prost"] }
