[package]
name = "xtask"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
toml_edit = "0.19.14"
prost-build = "0.11.9"
tonic-build = { version = "0.9.2", default-features = false, features = ["prost"] }
syn = "2.0.28"
prettyplease = "0.2.12"
