[package]
name = "xtask"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
toml_edit = "0.14"
prost-build = "0.10.1"
tonic-build = { version = "0.7.0", default-features = false, features = ["prost"] }
syn = "1.0"
prettyplease = "0.1"
