name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

# https://docs.github.com/ja/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        toolchain: [stable, nightly]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: arduino/setup-protoc@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
        profile: minimal
    - run: cargo build -v
    - run: cargo test -v
    - run: cargo xtask clean generate
