name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

# https://docs.github.com/ja/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        toolchain: [stable, nightly]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: arduino/setup-protoc@v2

      - run: |
          rustup set profile minimal
          rustup update --no-self-update ${{ matrix.toolchain }}
          rustup override set ${{ matrix.toolchain }}

      - run: cargo build
      - run: cargo test
      - run: cargo xtask clean generate
