name: doc

on:
  workflow_dispatch:
  push:
    tags: ['google-api-proto/v*']

# https://docs.github.com/ja/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doc:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: |
          rustup set profile minimal
          rustup update --no-self-update stable
          rustup override set stable

      - run: cargo doc --no-deps --all-features --package google-api-proto
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc/
