name: pub

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0,6,12,18 * * *'

jobs:
  pub:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: rustfmt
    - uses: arduino/setup-protoc@v1
    - run: cargo install cargo-release
    - run: ./pub.sh
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
