name: pub

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0,6,12,18 * * *'

# https://docs.github.com/ja/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pub:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        large-packages: false
        swap-storage: false
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        submodules: recursive
    - uses: arduino/setup-protoc@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
    - run: cargo install cargo-release
    - run: ./pub.sh
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
