name: publish

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: rustfmt
    - run: cargo build -v
    - run: cargo test -v
    - run: cargo xtask all
    - run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      working-directory: google-api-proto
    - run: cargo doc -v --no-deps --all-features --package google-api-proto
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc/
